language: cpp

jobs:
  include:
    - name: Ubuntu 18.04
      os: linux
      dist: bionic

    - name: Ubuntu 20.04
      os: linux
      dist: focal

    - name: Ubuntu 16.04
      os: linux
      dist: xenial

    - name: Windows 10
      os: windows
      env:
        - MSBUILD_PATH="c:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\16.0\Bin"
        - PATH_FIX="C:\Windows\System32"

    - name: XCode 11.4.1
      os: osx
      osx_image: xcode11.4

    - name: XCode 11.5
      os: osx
      osx_image: xcode11.5


before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get update;
      sudo apt-get -y install git wget unzip;
      sudo apt-get -y install build-essential software-properties-common cmake rsync libboost-all-dev;
    elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      echo "No before_install actions for OSX";
    elif [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      choco install visualstudio2019buildtools --package-parameters "--includeRecommended --includeOptional";
      choco install visualstudio2019-workload-vctools;
    fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      ./setup.sh;
      ./build.sh || travis_terminate 1;
      echo "Starting Unity Build!";
      (cd Unity && ./build.sh || travis_terminate 1);
    elif [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      export PATH=$MSBUILD_PATH:$PATH_FIX:$PATH;
      cmd.exe //C 'C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build\vcvarsall.bat' amd64 '&&'
      build.cmd '&&'
      cd Unity '&&' build.cmd;
    elif  [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      ./setup.sh;
      ./build.sh || travis_terminate 1;
      echo "Starting Unity Build!";
      (cd Unity && ./build.sh || travis_terminate 1);
    fi

  # Test ROS wrapper compilation
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      ./tools/install_ros_deps.sh;
      (cd ros && source ~/.bashrc && catkin build -DCMAKE_C_COMPILER=gcc-8 -DCMAKE_CXX_COMPILER=g++-8);
    fi
